app/routes/users.py
from flask import Blueprint, jsonify, render_template, redirect, url_for, request, abort
from flask_login import current_user, login_required, login_user, logout_user
from ..app_utils import required_clearance
from ..models import db, User

roles_bp = Blueprint('roles_bp', __name__, template_folder='../templates/users', url_prefix='/users')


@roles_bp.route('/')
@login_required
def users():
    registered_users = User.query.all()
    return render_template('users.html', registered_users=registered_users)

@roles_bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        name = request.form['username']
        password = request.form['password']
        clearance = request.form['clearance']
        user = User(name=name, password=password, clearance=clearance)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('roles_bp.login'))    
    return render_template('register.html')

@roles_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        name = request.form['username']
        password = request.form['password']
        user_about_to_login = db.session.query(User).filter_by(name=name).first()
        if user_about_to_login:
            if user_about_to_login.password == password:
                login_user(user_about_to_login)
                return redirect(url_for('roles_bp.users'))
            else:
                return jsonify({'msg':'Wrong password'})
        else:
            return jsonify({'msg':'No such user, register first'})
    # GET
    if current_user.is_authenticated:
        print(f'\nAlready logged in as: {current_user.name}\n')
        return redirect(url_for('roles_bp.users'))

    return render_template('login.html')

@roles_bp.route('/logout')
def logout():
    if current_user.is_authenticated:
        logout_user()
        return redirect(url_for('site.index'))
    else:
        return f'''<p>You are not logged in!</p><br><a href="{url_for('site.index')}">Home</a>'''

@roles_bp.route('/user/<int:user_id>', methods=['GET', 'POST'])
@login_required
def user(user_id):
    target_user = db.session.query(User).filter_by(id=user_id).first_or_404()
    if request.method == 'POST':
        # allow edit for admin and self
        if current_user.id == user_id or current_user.clearance == 1:
            new_username = request.form['username']
            target_user.name = new_username
            db.session.commit()
            return redirect(url_for('roles_bp.admin_dashboard'))
        else:
            abort(403)
    # GET - eject if request coming from different user
    if current_user.clearance == 1 or current_user.id == target_user.id:
        return render_template('user.html', user=target_user)
    else:
        abort(403)

@roles_bp.route('/delete/<int:user_id>', methods=['GET', 'POST'])
@required_clearance(2)
def delete_user(user_id):
    target_user = db.session.query(User).filter_by(id=user_id).first_or_404()
    if request.method == 'POST':
        # skipping asking for confirmation in production...
        if current_user.clearance == 1 or (current_user.clearance == 2 and target_user.clearance == 3):
            db.session.delete(target_user)
            db.session.commit()
            return redirect(url_for('roles_bp.admin_dashboard'))
        else:
            abort(403)
    else:
        return jsonify({'msg':'get request on delete endpoint...'})

@roles_bp.route('/managers_only')
@required_clearance(2)
def managers_only():
    non_admin_users = db.session.query(User).filter(User.clearance!=1).all()
    return render_template('managers_only.html', registered_users=non_admin_users)

@roles_bp.route('/admin_dashboard')
@required_clearance(1)
def admin_dashboard():
    registered_users = User.query.all()
    return render_template('admin_dashboard.html', registered_users=registered_users)

@roles_bp.route('/promote/<int:user_id>', methods=['POST'])
@required_clearance(2)
def promote(user_id):
    target_user = User.query.get_or_404(user_id)
    if target_user.clearance == 3:
        target_user.clearance -= 1
        db.session.commit()
        return redirect(url_for('roles_bp.managers_only'))
    else:
        return jsonify({'msg':'Nice try promoting to admin...'})

@roles_bp.route('/demote/<int:user_id>', methods=['POST'])
@required_clearance(2)
def demote(user_id):
    target_user = User.query.get_or_404(user_id)
    if target_user.clearance == 2:
        target_user.clearance += 1
        db.session.commit()
        return redirect(url_for('roles_bp.managers_only'))
    else:
        return jsonify({'msg':'Nice try promoting to admin...'})

app/templates/users/admin_dashboard.html
{% extends "base.html" %}

{% block title %}Admin Area{% endblock %}


{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title">
            Welcome back, Sir
        </h1>
        <h2 class="subtitle">Promote or demote employees, delete pleb accounts</h2>
    </div>
</section>

<section class="section">
    {% if registered_users %}
    <table class="table">
        <thead>
            <th>ID</th>
            <th>Name</th>
            <th>Clearance</th>
            <th>Actions</th>
        </thead>

        <tbody>
            {% for user in registered_users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.clearance }}</td>
                <td>
                    <a href="{{ url_for('roles_bp.user', user_id=user.id) }}" class="button">Edit</a>

                    {% if current_user.name == user.name %}
                    <form method="POST" action="{{ url_for('roles_bp.demote', user_id=user.id) }}">
                        <button class="button is-warning" type="submit" disabled>Demote to Employee</button>
                    </form>
                    <form method="POST" action="{{ url_for('roles_bp.promote', user_id=user.id) }}">
                        <button class="button is-success" type="submit" disabled>Promote to Manager</button>
                    </form>
                    <form method="POST" action="{{ url_for('roles_bp.delete_user', user_id=user.id) }}">
                        <button class="button is-danger" type="submit" disabled>Delete User immadiately</button>
                    </form>
                    {% else %}
                    <form method="POST" action="{{ url_for('roles_bp.demote', user_id=user.id) }}">
                        <button class="button is-warning" type="submit">Demote to Employee</button>
                    </form>
                    <form method="POST" action="{{ url_for('roles_bp.promote', user_id=user.id) }}">
                        <button class="button is-success" type="submit">Promote to Manager</button>
                    </form>
                    <form method="POST" action="{{ url_for('roles_bp.delete_user', user_id=user.id) }}">
                        <button class="button is-danger" type="submit">Delete User immadiately</button>
                    </form>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
    {% else %}
    <p>No users have registered yet. If you see this, authorization decoracor is not applied or has failed!</p>
    {% endif %}
</section>
{% endblock %}

app/templates/users/login.html
{% extends "base.html" %}

{% block title %}Login - Users{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <form method="POST">
            <label class="label">Username</label>
            <input type="text" name="username" placeholder="Enter username">

            <label class="label">Password</label>
            <input type="password" name="password" placeholder="Enter a dummy password">
            <br>
            <input type="submit" class="button">
        </form>
    </div>
</section>

{% endblock %}

app/templates/users/managers_only.html
{% extends "base.html" %}

{% block title %}Managers Area - Users{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <p class="title">Managers Area</p>
        <p class="subtitle">Promote or demote employees</p>
        <p class="content">You are logged in as: {{ current_user.name }}</p>
    </div>

    {% if registered_users %}
    <section class="section">
        <table class="table">
            <thead>
                <th>id</th>
                <th>username</th>
                <th>clearance</th>
                <th>promote</th>
                <th>demote</th>
            </thead>
            <tbody>
                {% for user in registered_users %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td>{{ user.name }}</td>
                    <td>{{ user.clearance }}</td>
                    {% if current_user.name == user.name %}
                    <td>
                        <form method="POST" action="{{ url_for('roles_bp.promote', user_id=user.id) }}">
                            <button class="button is-success" type="submit" value="Promote" disabled>Promote to
                                Manager</button>
                        </form>
                    </td>
                    <td>
                        <form method="POST" action="{{ url_for('roles_bp.demote', user_id=user.id) }}">
                            <button class="button is-warning" type="submit" value="Demote" disabled>Demote to
                                Employee</button>
                        </form>
                    </td>
                    {% else %}
                    <td>
                        <form method="POST" action="{{ url_for('roles_bp.promote', user_id=user.id) }}">
                            <button class="button is-success" type="submit" value="Promote">Promote to Manager</button>
                        </form>
                    </td>
                    <td>
                        <form method="POST" action="{{ url_for('roles_bp.demote', user_id=user.id) }}">
                            <button class="button is-warning" type="submit" value="Demote">Demote to Employee</button>
                        </form>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </section>
    {% else %}
    <p class="title">System error. You can not see this. This is members only. And.. we have no registered users if you
        are here. (??!!)</p>
    {% endif %}

</section>

{% endblock %}

app/templates/users/members_only.html
{% extends "base.html" %}

{% block title %}Members only area - Users{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <p class="title">Members area</p>
        <p class="content">You are logged in as: [to be added] {{ [] }}</p>
    </div>

    {% if registered_users %}
    <section class="section">
        <table class="table">
            <thead>
                <th>id</th>
                <th>username</th>
                <th>clearance</th>
            </thead>
            <tbody>
                {% for user in registered_users %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td>{{ user.name }}</td>
                    <td>{{ user.clearance }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </section>
    {% else %}
    <p class="title">System error. You can not see this. This is members only. And.. we have no registered users if you
        are here. (??!!)</p>
    {% endif %}

</section>

{% endblock %}

app/templates/users/register.html
{% extends "base.html" %}

{% block title %}Register - Users{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <form method="POST">
            <label class="label">Username</label>
            <input type="text" name="username" placeholder="Enter username">

            <label class="label">Password</label>
            <input type="password" name="password" placeholder="Enter a dummy password">

            <label class="label">Clearance</label>
            <input type="text" name="clearance" placeholder="Clearance level as: [1,2,3]">
            <br>
            <input type="submit" class="button">
        </form>
    </div>

    <section class="section">
        <div class="container">
            <p>Unhandled details:</p>
            <ul class="mt-4">
                <li>Dont register same username twice</li>
            </ul>
        </div>

    </section>
</section>

{% endblock %}

app/templates/users/user.html
{% extends "base.html" %}

{% block title %}Edit Profile - Users{% endblock %}

{% block content %}
<section class="section">
    <h1 class="title is-4">Edit profile</h1>
    <div class="container">
        <form method="POST">
            <label class="label">Change Username</label>
            <input type="text" name="username" placeholder="Enter new username" value="{{ user.name }}">
            <br>
            <input type="submit" class="button" value="Change username">
        </form>
    </div>
</section>

{% endblock %}

app/templates/users/users.html
{% extends "base.html" %}

{% block title %}Users{% endblock %}

{% block content %}
<section class="section">
    <div class="container mb-2">
        <p>You are logged in as: {{ current_user.name }}; your clearance level: {{ current_user.clearance }}</p>
    </div>

    <div class="container">
        <h2 class="title is-4">List of all registered users mortals can see</h2>
        {% if registered_users %}
        <ul>
            {% for user in registered_users %}
            {% if user.clearance != 1 %}
            <li>ID: {{ user.id }}; name: <strong><a href="{{ url_for('roles_bp.user', user_id=user.id) }}">{{ user.name }}</a></strong></li>
            {% endif %}
            {% endfor %}
        </ul>
        {% else %}
        <p>No users have registered yet. And you should not be looking here either way!</p>
        {% endif %}
    </div>
</section>
{% endblock %}