app/routes/products.py
from flask import Blueprint, url_for, render_template, request, jsonify, redirect
from app.models import db, Products, Brand


prod_bp = Blueprint('prod_bp', __name__, template_folder='../templates/products', url_prefix='/products')


@prod_bp.route('/', methods=['GET', 'POST'])
def products():
    if request.method == 'GET':
        items = db.session.query(Products).all()
        return render_template('products.html', products=items)

    if request.method == 'POST':
        id = request.form['id']
        name = request.form['name']
        qty = request.form['qty']
        brand_name = request.form['selected-brand']
        
        brand: Brand = db.session.query(Brand).filter(Brand.name==brand_name).first()
        new_item = Products(id=id, name=name, qty=qty, brand_name=brand.name) if id else Products(name=name, qty=qty, brand_name=brand_name)
        db.session.add(new_item)
        db.session.commit()
        return redirect(url_for('prod_bp.products'))

@prod_bp.route('/add_product')
def add_product():
    brands = [brand.name for brand in  Brand.query.all()]    
    return render_template('add_product.html', brands=brands)

@prod_bp.route('/<int:id>')
def product(id:int):
    prod = db.session.query(Products).filter(Products.id==id).first()
    return jsonify(prod.as_dict())

@prod_bp.route('/delete/<int:id>')
def delete(id:int):
    db.session.query(Products).filter(Products.id==id).delete()
    db.session.commit()
    return redirect(url_for('prod_bp.products'))

@prod_bp.route('/brands')
def brands():
    brands = [brand.name for brand in Brand.query.all()]
    return f'<h1>{brands}</h1>'

@prod_bp.route('/explore_brands')
def explore_brands():
    '''learning about queries, db models and foreign keys'''
    brand_entries = db.session.query(Brand).all()
    brand_products = [entry.products for entry in brand_entries]
    return f'<h1>{brand_products}</h1><br><h1>{brand_entries}</h1>'

app/templates/products/add_product.html
{% extends "base.html" %}


{% block title %}Add New Product{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        
        <form action="{{ url_for('prod_bp.products') }}" method="POST">
            <div class="field">
                <label class="label">ID</label>
                <div class="control">
                  <input class="input" type="text" name="id" placeholder="Enter ID">
                </div>
              </div>
    
              <div class="field">
                <label class="label">Name</label>
                <div class="control">
                  <input class="input" type="text" name="name" placeholder="Enter Name">
                </div>
              </div>
            
              <div class="field">
                <label class="label">Qty</label>
                <div class="control">
                  <input class="input" type="text" name="qty" placeholder="Enter quantity">
                </div>
              </div>
            
              <div class="select">
                <select name="selected-brand">
                  {% for brand in brands %}
                  <option>{{ brand }}</option>
                  {% endfor %}
                </select>
              </div>
              <input type="submit" class="button">
        
        </form>
    </div>
</section>

{% endblock %}

app/templates/products/products.html
{% extends "base.html" %}

{% block title %}Products{% endblock %}


{% block content %}

<section class="section">
    <a href="{{ url_for('prod_bp.add_product') }}" class="button">Add new product</a>
</section>

<section class="section">

    {% if products %}

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Brand</th>
                <th>Qty</th>
            </tr>
        </thead>
        <tbody>

            {% for product in products %}
            <tr>
                <td>{{ product.id }}</td>
                <td><a href="{{ url_for('prod_bp.product', id=product.id) }}">{{ product.name }}</a></td>
                <td>{{ product.brand.name }}</td>
                <td>{{ product.qty }} <a href="{{ url_for('prod_bp.delete', id=product.id) }}"><button
                            class="delete"></button></td></a>
            </tr>
            {% endfor %}

        </tbody>
    </table>
    {% else %}
    <div class="notification is-warning">
        Currently no items are in database. Add one!
    </div>

    {% endif %}

</section>

{% endblock %}