app/routes/files.py
import os
from flask import Blueprint, redirect, render_template, request
from flask import send_from_directory, url_for, current_app
from werkzeug.utils import secure_filename
from app.models import UploadFile
from app.extensions import db
from app.app_utils import read_workbook

files_bp = Blueprint('files_bp', __name__, template_folder='../templates/files', url_prefix='/files')

ALLOWED_EXTENSIONS = {'csv', 'txt', 'xlsx'}

def allowed_file(fname:str) -> bool:
    '''returns True if path is valid and file extension is one of allowed'''
    return '.' in fname and fname.rsplit('.', 1)[-1].lower() in ALLOWED_EXTENSIONS

@files_bp.route('/')
def get_files():
    up_fs = db.session.query(UploadFile).all()
    return render_template('files.html', up_fs=up_fs)

@files_bp.route('/upload', methods=['GET', 'POST'])
def upload_file():
    '''dropzone posts to same route. Fixing that is a pain in js or new plugin (flask-dropzone)'''
    if request.method == 'POST':
        files = request.files.getlist('file')
        xlsx_values = []
        files_uploaded_counter = 0
        did_some_work = False
        for i, file in enumerate(files, start=1):
            print(f'\n---Iterating files--- f: {file}, filename attr: {file.filename}\n')
            if file.filename == '':
                print('\nNo file selected!\n')
                if i == len(files) and not did_some_work:
                    return '<h1>submited without selected files. Handled on wtf-form validators in real cases</h1>'
                else:
                    continue
            
            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)            
                save_to_path = os.path.join(current_app.root_path, current_app.config['UPLOAD_FOLDER'], filename)
                # save_to_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
                file.save(save_to_path)

                # additionally collect data from  xlsx files
                if save_to_path.lower().endswith('.xlsx'):
                    val_from_wb = read_workbook(save_to_path)
                    xlsx_values.append(val_from_wb)

                upload_file = UploadFile(filename=filename, fpath=save_to_path, user_upload=False)
                db.session.add(upload_file)
                files_uploaded_counter += 1
                did_some_work = True
        db.session.commit()
        print(f'saved file: {filename} to db. Do I redirect?')
        msg = f'Successfully uploaded {files_uploaded_counter} files'
        return redirect(url_for('files_bp.upload_processing'))
        # return render_template('upload_processing.html', )
    
    # GET 
    accepted_exts = ', '.join(ALLOWED_EXTENSIONS)
    return render_template('upload_file.html', accepted_exts=accepted_exts)

@files_bp.route('/upload_processing')
def upload_processing():
    return render_template('upload_file.html')

@files_bp.route('/download_file/<int:id>')
def download_file(id:int):
    f_for_download = UploadFile.query.get_or_404(id)
    return send_from_directory(current_app.config['UPLOAD_FOLDER'], f_for_download.filename,
        download_name=f_for_download.filename, as_attachment=True)

app/templates/files/files.html
{% extends "base.html" %}

{% block title %}Files{% endblock %}

{% block content %}
<section class="section">
    <a href="{{ url_for('files_bp.upload_file') }}" class="button">Upload New File</a>

    <div class="container">
        {% if up_fs %}
        <h1 class="title is-4">List of available files</h1>
        <p>Click to download</p>
        <ol>
            {% for up_fs in up_fs %}
            <li>
                <a href="{{ url_for('files_bp.download_file', id=up_fs.id) }}">{{ up_fs.filename }}</a>
                (uploaded on: {{ up_fs.upload_date }})
            </li>
            {% endfor %}
        </ol>

        {% else %}
        <div class="notification is-warning">
            Currently no items are in database. Add one!
        </div>
        {% endif %}
    </div>
</section>
{% endblock %}

app/templates/files/upload_file.html
{% extends "base.html" %}

{% block title %}Upload New File{% endblock %}

{% block head_import %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.1/min/dropzone.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="is-title is-4">Upload new file(s)</h1>
</div>

<div class="container has-text-centered has-text-danger has-text-weight-semibold">
    Accepted files: {{ accepted_exts }}
</div>

<div class="container">
    <form action="{{ url_for('files_bp.upload_file') }}" class="dropzone" method="POST" id="dropzone" enctype="multipart/form-data">
    </form>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.1/min/dropzone.min.js"></script>
</div>

{% endblock %}

app/templates/files/upload_processing.html
{% extends "base.html" %}

{% block title %}Files{% endblock %}

{% block content %}
<section class="section">
    <div class="block">
        <div class="notification is-success">{{ msg }}</div>
    </div>
    {% if xlsx_values %}
    <div class="block">
        <p class="content">These are the values from excel A2 cells:</p>
        <br>
        {% for val in xlsx_values %}
        <p>{{ val }}</p>
        {% endfor %}
    </div>

    {% else %}
    <div class="notification is-info">
        No excel files in your uploads.
    </div>
    {% endif %}
</section>
{% endblock %}