app/routes/__init__.py
from flask import Blueprint, render_template


site = Blueprint('site', __name__)


@site.route('/')
def index():
    return render_template('index.html')

@site.route('/bulma')
def bulma():
    return render_template('bulma.html')

app/routes/files.py
import os
from flask import Blueprint, redirect, render_template, request
from flask import send_from_directory, url_for, current_app
from werkzeug.utils import secure_filename
from app.models import UploadFile
from app.extensions import db
from app.app_utils import read_workbook

files_bp = Blueprint('files_bp', __name__, template_folder='../templates/files', url_prefix='/files')

ALLOWED_EXTENSIONS = {'csv', 'txt', 'xlsx'}

def allowed_file(fname:str) -> bool:
    '''returns True if path is valid and file extension is one of allowed'''
    return '.' in fname and fname.rsplit('.', 1)[-1].lower() in ALLOWED_EXTENSIONS

@files_bp.route('/')
def get_files():
    up_fs = db.session.query(UploadFile).all()
    return render_template('files.html', up_fs=up_fs)

@files_bp.route('/upload', methods=['GET', 'POST'])
def upload_file():
    '''dropzone posts to same route. Fixing that is a pain in js or new plugin (flask-dropzone)'''
    if request.method == 'POST':
        files = request.files.getlist('file')
        xlsx_values = []
        files_uploaded_counter = 0
        did_some_work = False
        for i, file in enumerate(files, start=1):
            print(f'\n---Iterating files--- f: {file}, filename attr: {file.filename}\n')
            if file.filename == '':
                print('\nNo file selected!\n')
                if i == len(files) and not did_some_work:
                    return '<h1>submited without selected files. Handled on wtf-form validators in real cases</h1>'
                else:
                    continue
            
            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)            
                save_to_path = os.path.join(current_app.root_path, current_app.config['UPLOAD_FOLDER'], filename)
                # save_to_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
                file.save(save_to_path)

                # additionally collect data from  xlsx files
                if save_to_path.lower().endswith('.xlsx'):
                    val_from_wb = read_workbook(save_to_path)
                    xlsx_values.append(val_from_wb)

                upload_file = UploadFile(filename=filename, fpath=save_to_path, user_upload=False)
                db.session.add(upload_file)
                files_uploaded_counter += 1
                did_some_work = True
        db.session.commit()
        print(f'saved file: {filename} to db. Do I redirect?')
        msg = f'Successfully uploaded {files_uploaded_counter} files'
        return redirect(url_for('files_bp.upload_processing'))
        # return render_template('upload_processing.html', )
    
    # GET 
    accepted_exts = ', '.join(ALLOWED_EXTENSIONS)
    return render_template('upload_file.html', accepted_exts=accepted_exts)

@files_bp.route('/upload_processing')
def upload_processing():
    return render_template('upload_file.html')

@files_bp.route('/download_file/<int:id>')
def download_file(id:int):
    f_for_download = UploadFile.query.get_or_404(id)
    return send_from_directory(current_app.config['UPLOAD_FOLDER'], f_for_download.filename,
        download_name=f_for_download.filename, as_attachment=True)

app/routes/tasks.py
from flask import Blueprint, render_template, request
from ..ctasks import get_unique_id_with_delay

tasks_bp = Blueprint('tasks_bp', __name__, template_folder='../templates/tasks', url_prefix='/tasks')


@tasks_bp.route('/')
def tasks():
    '''display active tasks, option to create new task or enter results page'''    
    # CREATE NEW TASK
    return render_template('tasks.html')


@tasks_bp.route('/results/', methods=['POST'])
def results():
    if request.method == 'POST':
        # get time, pass to task, pass result to results.html
        delay = int(request.form['delay'])
        get_unique_id_with_delay(delay)
        
        # something = celery_in.apply(get_unique_id_with_delay, delay=delay)
        # result = get_unique_id_with_delay(delay=delay)
        something = 'boo'
        return render_template('results.html', result=something)

app/routes/users.py
from flask import Blueprint, jsonify, render_template, redirect, url_for, request, abort
from flask_login import current_user, login_required, login_user, logout_user
from ..app_utils import required_clearance
from ..models import db, User

roles_bp = Blueprint('roles_bp', __name__, template_folder='../templates/users', url_prefix='/users')


@roles_bp.route('/')
@login_required
def users():
    registered_users = User.query.all()
    return render_template('users.html', registered_users=registered_users)

@roles_bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        name = request.form['username']
        password = request.form['password']
        clearance = request.form['clearance']
        user = User(name=name, password=password, clearance=clearance)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('roles_bp.login'))    
    return render_template('register.html')

@roles_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        name = request.form['username']
        password = request.form['password']
        user_about_to_login = db.session.query(User).filter_by(name=name).first()
        if user_about_to_login:
            if user_about_to_login.password == password:
                login_user(user_about_to_login)
                return redirect(url_for('roles_bp.users'))
            else:
                return jsonify({'msg':'Wrong password'})
        else:
            return jsonify({'msg':'No such user, register first'})
    # GET
    if current_user.is_authenticated:
        print(f'\nAlready logged in as: {current_user.name}\n')
        return redirect(url_for('roles_bp.users'))

    return render_template('login.html')

@roles_bp.route('/logout')
def logout():
    if current_user.is_authenticated:
        logout_user()
        return redirect(url_for('site.index'))
    else:
        return f'''<p>You are not logged in!</p><br><a href="{url_for('site.index')}">Home</a>'''

@roles_bp.route('/user/<int:user_id>', methods=['GET', 'POST'])
@login_required
def user(user_id):
    target_user = db.session.query(User).filter_by(id=user_id).first_or_404()
    if request.method == 'POST':
        # allow edit for admin and self
        if current_user.id == user_id or current_user.clearance == 1:
            new_username = request.form['username']
            target_user.name = new_username
            db.session.commit()
            return redirect(url_for('roles_bp.admin_dashboard'))
        else:
            abort(403)
    # GET - eject if request coming from different user
    if current_user.clearance == 1 or current_user.id == target_user.id:
        return render_template('user.html', user=target_user)
    else:
        abort(403)

@roles_bp.route('/delete/<int:user_id>', methods=['GET', 'POST'])
@required_clearance(2)
def delete_user(user_id):
    target_user = db.session.query(User).filter_by(id=user_id).first_or_404()
    if request.method == 'POST':
        # skipping asking for confirmation in production...
        if current_user.clearance == 1 or (current_user.clearance == 2 and target_user.clearance == 3):
            db.session.delete(target_user)
            db.session.commit()
            return redirect(url_for('roles_bp.admin_dashboard'))
        else:
            abort(403)
    else:
        return jsonify({'msg':'get request on delete endpoint...'})

@roles_bp.route('/managers_only')
@required_clearance(2)
def managers_only():
    non_admin_users = db.session.query(User).filter(User.clearance!=1).all()
    return render_template('managers_only.html', registered_users=non_admin_users)

@roles_bp.route('/admin_dashboard')
@required_clearance(1)
def admin_dashboard():
    registered_users = User.query.all()
    return render_template('admin_dashboard.html', registered_users=registered_users)

@roles_bp.route('/promote/<int:user_id>', methods=['POST'])
@required_clearance(2)
def promote(user_id):
    target_user = User.query.get_or_404(user_id)
    if target_user.clearance == 3:
        target_user.clearance -= 1
        db.session.commit()
        return redirect(url_for('roles_bp.managers_only'))
    else:
        return jsonify({'msg':'Nice try promoting to admin...'})

@roles_bp.route('/demote/<int:user_id>', methods=['POST'])
@required_clearance(2)
def demote(user_id):
    target_user = User.query.get_or_404(user_id)
    if target_user.clearance == 2:
        target_user.clearance += 1
        db.session.commit()
        return redirect(url_for('roles_bp.managers_only'))
    else:
        return jsonify({'msg':'Nice try promoting to admin...'})

app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %} - Flask Cases</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    {% block head_import %}{% endblock %}
</head>

<body>
    <div class="container has-text-centered">
        <h2 class="title is-4"><a href="{{ url_for('site.index') }}">Home</a></h3>
    </div>
    <div class="container has-text-centered">
        <h2 class="title is-4"><a href="{{ url_for('site.bulma') }}">Mess with Bulma</a></h3>
    </div>

    <div class="tabs is-centered">
        <p class="title is-5 is-pulled-left">Products</p>
        <ul>
            <li><a href="{{ url_for('prod_bp.products') }}">products</a></li>
            <li><a href="{{ url_for('prod_bp.add_product') }}">add product</a></li>
            <li>product/id (pick at products)</li>
        </ul>
    </div>

    <div class="tabs is-centered">
        <p class="title is-5 is-pulled-left">User Roles</p>
        <ul>
            <li><a href="{{ url_for('roles_bp.users') }}">users</a></li>
            <li><a href="{{ url_for('roles_bp.register') }}">register</a></li>
            <li><a href="{{ url_for('roles_bp.login') }}">login</a></li>
            <li><a href="{{ url_for('roles_bp.logout') }}">logout</a></li>
            <li><a href="{{ url_for('roles_bp.managers_only') }}">managers only</a></li>
            <li><a href="{{ url_for('roles_bp.admin_dashboard') }}">admin area</a></li>
            <li>user/id (pick at users)</li>
        </ul>
    </div>


    <div class="tabs is-centered">
        <p class="title is-5 is-pulled-left">Static files</p>
        <ul>
                <li><a href="{{ url_for('files_bp.get_files') }}">available files</a></li>
                <li><a href="{{ url_for('files_bp.upload_file') }}">upload file</a></li>
            </ul>
    </div>


    {% block content %}{% endblock %}

</body>

</html>

app/templates/bulma.html
{% extends "base.html" %}

{% block title %}Front-end experiments{% endblock %}


{% block content %}

<section class="section">
    <div class="container">

        <article class="message is-success">
            <div class="message-header">
              <div>message header</div>
              <div>second</div>
              <div>third</div>
              <div>right?</div>

            </div>
            <div class="message-body content">
                <h2>heading2</h2>
                <p>Lorem ipsum dolor sit amet.</p>
                <h4>heading4</h4>
                <p>Chill yo</p>

                <ul>
                    <li>bla1</li>
                    <li>bla2</li>
                    <li>bla3</li>
                </ul>

                <h4>Deleted stuff:</h4>
                <pre>
                    deleted1
                    deleted2
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime officia facere delectus commodi id enim soluta blanditiis sint fuga. Asperiores!
                </pre>

            </div>
          </article>


    </div>
</section>

{% endblock %}

app/templates/fuck_tiles.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Duck the Tiles</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/57b41a2f3a.js" crossorigin="anonymous"></script>
</head>

<body>
    <section class="section">
        <div class="container">
            <div class="tile is-ancestor">

                <a class="tile is-4 box mx-2" href="#">
                    <div class="content">
                        <h4>Product_1</h4>
                        <p><strong>Detail_1: </strong>Value_1</p>
                        <p><strong>Detail_2: </strong>Value_2</p>
                        <p>...</p>
                    </div>
                </a>

                <a class="tile is-4 box mx-2" href="">
                    <div class="content has-text-centered m-auto">
                        <h4>Add New</h4>
                        <p>
                            <span class="icon is-large">
                                <i class="fa-solid fa-plus fa-2x"></i>
                            </span>
                        </p>
                    </div>
                </a>
                
            </div>
        </div>
    </section>

</body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="container">
    <div class="card mb-6">
        <header class="card-header">
            <a href="{{ url_for('prod_bp.products') }}" class="title is-4">Products</a>
        </header>
        <div class="content mt-4">
            Simple products CRUD
        </div>
    </div>

    <div class="card mb-6">
        <header class="card-header">
            <a href="{{ url_for('roles_bp.register') }}" class="title is-4">Users and Roles</a>
        </header>
        <div class="content mt-4">
            Register, login via flask-login. Use of @login_required decorator as well as
            custom role limiting on routes
        </div>
    </div>

    <div class="card mb-6">
        <header class="card-header">
            <a href="{{ url_for('files_bp.get_files') }}" class="title is-4">Files</a>
        </header>
        <div class="content mt-4">
            Upload, view and download static files
        </div>
    </div>

    <div class="card mb-6">
        <header class="card-header">
            <a href="{{ url_for('tasks_bp.tasks') }}" class="title is-4">Celery Tasks</a>
        </header>
        <div class="content mt-4">
            Create new tasks for celery, retrieve results, schedule tasks?
        </div>
    </div>

    
</div>
{% endblock %}